# Site settings
title: yuyangyang Blog
header-img: img/home-bg.jpg
email: yuyang041060120@gmail.com
copyright_name: YangYang Yu
description: "yuyangyang blog,share my experiences and thoughts with all"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: yuyang041060120
github_username:  yuyang041060120
email_username:  yuyang041060120@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
